### ISSUE TITLE
Issues with using plugin in latest version of Atom (0.175.0)

### ISSUE THREAD

**Issue by rmmeans** [jpohjolainen/atom-hiera-eyaml#1]
I'm getting errors using this tool in the latest versions of Atom(0.175.0). 

See message below generated by atom for this issue:

---

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom 2.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/rmeans/.atom/packages/hiera-eyaml/lib/main.coffee:34:9)
```

**Comment by jpohjolainen** [comment]
Hi, thanks for informing this. New version 0.4.6 has this fixed.
