### ISSUE TITLE
Support for key profiles

### ISSUE THREAD

**Issue by af6140** [jpohjolainen/atom-hiera-eyaml#8]
Scenario: Users working with multiple environment/profiles with different public/private keys. Provide settings and menu for switch between profiles.

**Comment by emarcellus** [comment]
Another vote for multiple profiles.

**Comment by af6140** [comment]
@emarcellus , i created one plugin to support key profiles, it's available at https://github.com/af6140/atom-eyaml-profiles

**Comment by af6140** [comment]
Since we have alternative, closing issue.
